services:
  api:
    container_name: api-endpoints
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
    networks:
      - aira-network
  frontend:
    container_name: ai-chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://api:8000
    depends_on:
      - api
    networks:
      - aira-network
  docs:
    container_name: docs
    build: ./docs
    ports:
      - "3005:3005"
    command: npm start
    depends_on:
      - api
    networks:
      - aira-network

  qdrant:
    container_name: qdrant-service
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    env_file:
      - .env
    networks:
      - aira-network

networks:
  aira-network:
    driver: bridge
